name: Docker Build, Upload to ECR
run-name: ${{ github.actor }} 🚀

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 448066611421.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: seohyun-test

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
    - name: SSH into EC2 and deploy
      env:
        EC2_HOST: 43.201.72.173
        EC2_USER: ec2-user
        SSH_PRIVATE_KEY: ${{ secrets.SSH_EC2_SECRET_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY' > temp.pem
        chmod 600 temp.pem
        ssh -i temp.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USER@$EC2_HOST "docker stop $(docker ps -q) && docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest && docker run -d -p 3000:3000 $ECR_REGISTRY/$ECR_REPOSITORY:latest"

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: 43.201.72.173
    #     username: ec2-user
    #     key: ${{ secrets.SSH_EC2_SECRET_KEY }}
    #     script: |
    #       for container_id in $(docker ps -q); do
    #         docker stop $container_id
    #         docker rm $container_id
    #       done

    #       image_reference="$ECR_REGISTRY/$ECR_REPOSITORY:latest"
    #       docker pull $image_reference
    #       docker run -d -v /etc/localtime:/etc/localtime:ro -e TZ=Asia/Seoul -p 3000:3000 $image_reference